### PR TITLE
function elica intubata 2

### PR DESCRIPTION
**Pull request by ChristianSalzano**

### CODE REVIEW

**Comment by ChristianSalzano** [comment]
@EttoreSaetta me and @CMirabella180890 changed the function which is now ready for a review.

**Comment by EttoreSaetta** [comment]
@ChristianSalzano it's nice to see the interface with the other function for the ring vortex.
In the documentation you should add an example of execution of your function.
Change the name of the documentation file, it should be something referred to your function.
There are some useless files `.DS_Store`

**Comment by ChristianSalzano** [comment]
@EttoreSaetta me and @CMirabella180890 added an example of the execution of the function in the documentation, changed its name in documentation_ducted_prop_thrust and deleted the useless files.

**Review by EttoreSaetta — APPROVED** [review]
LGTM

**Pull request merged**
